- name: PostProvisionSample
  hosts: localhost
  vars:
    - manageiq_validate_certs: false
    - manageiq_connection:
          url: 'https://localhost:3000'
          username: 'admin'
          password: 'password'
          automate_workspace: 'automate_workspaces/1234'
          manageiq_validate_certs: false
  roles:
    - role: '/runner/project/roles/manageiq.manageiq_automate'
  tasks:
   - name: GET
     ansible.builtin.uri:
       url: http://mcm-demo-api-service.mcm-demo-api.svc.cluster.local/api/hello
   - name: POST
     ansible.builtin.uri:
       url: http://mcm-demo-api-service.mcm-demo-api.svc.cluster.local/items/
       method: POST
       body: >-
        {{ {"name": "hello",
             "id": "hi",
            } }}
       body_format: json
       validate_certs: no
