- name: PostProvisionSample
  hosts: localhost
  vars:
    - manageiq_validate_certs: false
  roles:
    - manageiq-core.manageiq-automate
  tasks:
   - name: GET
     ansible.builtin.uri:
       url: http://mcm-demo-api-service.mcm-demo-api.svc.cluster.local/api/hello
   - name: POST
     ansible.builtin.uri:
       url: http://mcm-demo-api-service.mcm-demo-api.svc.cluster.local/items/
       method: POST
       body: >-
        {{ {"name": "hello",
             "id": "hi",
            } }}
       body_format: json
       validate_certs: no
